# SITE CONFIGURATION
baseurl: "/artportal.github.io/" # the subpath of your site, e.g. /blog/
url: "https://sokolovadasha.github.io" # the base hostname & protocol for your site
# THEME_SETTINGS-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: > 
      Изостудия Арт Портал
      г. Владимир
  avatar: logo-mini-invisible.png
  description: # used by search engines

  # Header and footer text
  header_text: >
     <h2>Изостудия Арт Портал</h2>
     <h3>Академическая школа живописи и рисунка</h3>
     <h3>Дизайн и декоративное искусство</h3>
     <p>г. Владимир</p> 

  footer_text: >
     <p>Изостудия Арт Портал. Рисование для детей и взрослых во Владимире</p>
     В оформлении сайта используются фрагменты картин 
     художника <a href="/surikov_victor_borisovich/">Сурикова Виктора Борисовича.</a> 

  header_text_feature_image: "img/feature-img/amur_hmuritsia_1971_27_45_3.jpg"

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:
  vk: "artstud33"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Следующая"
  str_prev: "Предыдущая"
  str_continue_reading: "Читать далее"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Open+Sans:400&subset=cyrillic"

  # Post navigation
  post_navigation: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      feature-img: "img/sample_feature_img_3.jpg"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# BUILD SETTINGS
sass:
  sass_dir: _sass
  style: :compressed
